# Sidekiq schedule configuration
# Format: job_name: { cron: 'cron_expression', class: 'JobClass', queue: 'queue_name' }

# Daily data cleanup and maintenance
cleanup_old_audit_logs:
  cron: '0 2 * * *'  # Daily at 2 AM
  class: CleanupAuditLogsJob
  queue: low

cleanup_old_cache:
  cron: '0 3 * * *'  # Daily at 3 AM
  class: CleanupCacheJob
  queue: low

# Performance monitoring and metrics
generate_daily_reports:
  cron: '0 6 * * *'  # Daily at 6 AM
  class: GenerateDailyReportsJob
  queue: default

cleanup_old_metrics:
  cron: '0 4 * * *'  # Daily at 4 AM
  class: CleanupMetricsJob
  queue: low

# Data backup and archiving
backup_database:
  cron: '0 1 * * 0'  # Weekly on Sunday at 1 AM
  class: DatabaseBackupJob
  queue: low

archive_old_transactions:
  cron: '0 5 * * 1'  # Weekly on Monday at 5 AM
  class: ArchiveTransactionsJob
  queue: low

# Health checks and monitoring
system_health_check:
  cron: '*/15 * * * *'  # Every 15 minutes
  class: SystemHealthCheckJob
  queue: critical

cache_health_check:
  cron: '*/10 * * * *'  # Every 10 minutes
  class: CacheHealthCheckJob
  queue: critical

# Data synchronization
sync_restaurant_data:
  cron: '*/30 * * * *'  # Every 30 minutes
  class: SyncRestaurantDataJob
  queue: default

# Analytics and reporting
generate_hourly_analytics:
  cron: '0 * * * *'  # Every hour
  class: GenerateHourlyAnalyticsJob
  queue: default

# Maintenance tasks
vacuum_database:
  cron: '0 0 * * 0'  # Weekly on Sunday at midnight
  class: VacuumDatabaseJob
  queue: low

update_search_indexes:
  cron: '0 7 * * *'  # Daily at 7 AM
  class: UpdateSearchIndexesJob
  queue: default
